GET http://localhost:3001/api/checklist

### 

POST http://localhost:3001/api/checklist
Content-Type: application/json

{
    "description": "Wheels not wobbling"
}

###

PATCH http://localhost:3001/api/checklist/62acb25c2281510813b0df73
Content-Type: application/json

{
    "description": "Identification plate fitted."
}

###

DELETE http://localhost:3001/api/checklist/62abe24e2af20a09663cdb37

###

DELETE http://localhost:3001/api/checklist
Content-Type: application/json

[
    "62ac6c862281510813b0df69", "62aca17c2281510813b0df70"
]
