GET http://localhost:3001/api/users

### 

GET http://localhost:3001/api/users/


###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Saskia",
    "email": "sas@kia",
    "phoneNumber": "09876543210",
    "password": "!23Qwe"
}

###

POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "login": "mateusz.harlos@gmail.com",
    "password": "!23Qwe"
}

###

PUT http://localhost:3001/api/users/6216221627390ea38837389c
Content-Type: application/json

{
    "password": "!23Qwe"
}

###
PUT http://localhost:3001/api/users/updateAsAdmin/6216221627390ea38837389c
Content-Type: application/json

{
    "line_3": "blablabla"
}

###

DELETE http://localhost:3001/api/users/6256bbf0c737137226bbe42d

###
GET https://parseapi.back4app.com/
X-Parse-Application-Id: 4oFovioSMOe1CJiiw8UeO3FdHEkHbka7FZx2awzn
X-Parse-REST-API-Key: Rszcv5J1Q794frmM5Qrt4JHJizmP0WPdti70vvQN
Content-Type: application/json

###
POST http://localhost:3001/api/users/testForDuplicate
Content-Type: application/json

{
    "_id" : "6216221627390ea38837389c",
    "email": "tedros@gmail.com"
}